import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { Toaster } from "react-hot-toast";
import AuthCheker from "@/components/Auth/auth-checker";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TaskPro | Gestion de proyectos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Header />
        <Toaster position="bottom-center" />

        <div className="bg-white h-screen">
          <AuthCheker>{children}</AuthCheker>
        </div>
      </body>
    </html>
  );
}
